# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cyclone/all/cyclone.rbi
#
# cyclone-0.1.0

class Rational < Numeric
  def next_sample(*args, &blk); end
  def sample(*args, &blk); end
  def whole_cycle(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
